### PR TITLE
RFC - feat(action-resolver): create an improved action resolver for simpler handling of actions

### PR DESCRIPTION
**Pull request by Jamiewarb**
# Context

Document Actions allow for the addition of new document actions, or the modification of existing ones.

However, managing multiple document actions that may cover multiple schema types can be verbose, leading to configuration that is hard to read.

# Overview

The premise of this PR is to provide an improved API to document actions. It also ensures an escape hatch to manually manage certain document actions if needed, while maintaining the new API for other document actions. End users of course can opt not to use it entirely, and maintain manual management of all document actions.

## Examples

This API works best when you're modifying existing Sanity document actions. If you're only adding new ones, you won't need this at all.

```ts
export const documentActions = resolveActionsPipeline([
  /** Add list of modifiers here, defined using `modifyAction()` */
  modifyAction({
    actions: ['publish'],
    handler: (action) => changePublishText(action, 'Update'),
  }),
  modifyAction({
    actions: ['publish'],
    schemaTypes: ['page', 'article'],
    handler: generateSlugAction,
  }),
  modifyAction({
    actions: ['publish'],
    schemaTypes: ['article'],
    handler: setPublishDateAction,
  }),
  modifyAction({
    actions: ['publish'],
    schemaTypes: ['article', 'book'],
    handler: setReadingTimeAction,
  }),
  newAction({
    schemaTypes: ['page'],
    actionComponent: exportTranslationAction,
  }),
]);
```

## Setup

To set up the Document Resolver API, add a function to your `document.actions` key in `sanity.config.ts`:

```ts
document: {
  actions: documentActions,
},
```

The `documentActions` function should in turn call the `resolveActionsPipeline` function from `@pkg/sanity-toolkit/studio/actions/resolver`

```ts
import { DocumentActionsResolver } from 'sanity';
import { resolveActionsPipeline } from '@pkg/sanity-toolkit/studio/actions/resolver';

// See: https://www.sanity.io/docs/document-actions

export const documentActions = resolveActionsPipeline([]);
```

You're now ready to use the Action Resolver API

### Modifying Existing Actions

Action Modifiers are added to the array in the third parameter of the `resolveActionsPipeline` call.

An Action Modifier describes a modifier function for one or more actions. It can optionally be filtered by action or by schema type.

In its simplest form, an Action Modifier is an object with a `handler` callback:

```ts
const actionLogger = {
  handler: (action) => { console.log(action); return action; },
};
```

The above Action Modifier will log out each DocumentActionComponent, without modifying the list. It will be called for every action currently in the list of actions, as well as for every schema type.

It can be optionally filtered to specific actions or schema types too:

```ts
const actionLogger = {
  actions: ['publish'],
  schemaTypes: ['page', 'article'],
  handler: (action) => { console.log(action); return action; },
};
```

This will now only be called with the `publish` action, and only when opening documents of type `page` or `article` in Sanity.

A less contrived example may be changing the "Publish" label of the publish action to read "Update" for documents that have already been published.

```ts
const useLabelPublishOrUpdate = modifyAction({
  actions: ['publish'],
  handler: (action) => changePublishText(action, 'Update'), // Use "Update" if document already published
});
```

Here we're also using the helper function `modifyAction`, which provides full typing to our object.

Lastly, if you do not have any actions or schemaTypes you wish to filter by, you can return just the handler function:

```ts
const useLabelPublishOrUpdate = modifyAction((action) => changePublishText(action, 'Update'));
```

---

If you need more control over the finalised actions array, you can use the `resolveActionsPipeline` function directly (as opposed to `resolveActionsPipeline`). This requires you to pass the `actions` and `context` parameters to it, but in return have more flexibility over the final output, to add further document actions to the array.

```ts
export const documentActions: DocumentActionsResolver = (previousActions, context) => {
  return resolveActionsPipeline(
    previousActions,
    context,
    /** Add list of modifiers here, defined using `modifyAction()` */
    [useLabelPublishOrUpdate],
  );
};
```

### Adding New Actions

You can also use this API to add new document actions, to all documents or just to documents of a particular schema type.

You can do this using the `newAction()` helper:

```ts
export const documentActions = resolveActionsPipeline([
  /** Add list of modifiers here, defined using `modifyAction()` or `newAction()` */
  newAction({
    schemaTypes: ['page'],
    actionComponent: exportTranslationAction,
  }),
]);
```

This will add a new Document Action to all Pages, as the last item in the list.

### Further flexibility on document actions

If further flexibility is required, `resolveActionsPipeline` takes a callback as a second parameter. This can be used to modify the final array before it is returned to Sanity config:

```ts
export const documentActions = resolveActionsPipeline([
  /** Add list of modifiers here, defined using `modifyAction()` or `newAction()` */
  modifyAction({
    actions: ['publish'],
    handler: (action) => changePublishText(action, 'Update'), // Use "Update" if document already published
  }),
], (actions, context) => {
  return actions; // Modify this array as required, such as re-ordering items.
});
```

## Alternative

From the original example above:

```ts
export const documentActions = resolveActionsPipeline([
  /** Add list of modifiers here, defined using `modifyAction()` */
  modifyAction({
    actions: ['publish'],
    handler: (action) => changePublishText(action, 'Update'),
  }),
  modifyAction({
    actions: ['publish'],
    schemaType: ['page', 'article'],
    handler: generateSlugAction,
  }),
  modifyAction({
    actions: ['publish'],
    schemaType: ['article'],
    handler: setPublishDateAction,
  }),
  modifyAction({
    actions: ['publish'],
    schemaType: ['article', 'book'],
    handler: setReadingTimeAction,
  }),
  newAction({
    schemaTypes: ['page'],
    actionComponent: exportTranslationAction,
  }),
]);
```

The alternative looks something like this:

```ts
const documentActions = DocumentActionsResolver = (actions, context) => {
  let newActions = [...actions];

  newActions = newActions.map((originalAction) => {
    if (originalAction.action === 'publish') {
      let action = originalAction;

      action = changePublishText(action, 'Update');

      if (['page', 'article'].includes(context.schemaType)) {
        action = generateSlugAction(action);
      }

      if (['article'].includes(context.schemaType)) {
        action = setPublishDateAction(action);
      }

      if (['article', 'book'].includes(context.schemaType)) {
        action = setReadingTimeAction(action);
      }

      return action;
    }

    return originalAction;
  });

  const exportTranslationDocAction = ['page'].includes(context.schemaType) ? [exportTranslationAction] : [];

  return [
    ...newActions,
    ...exportTranslationDocAction,
  ];
};
```

It's slightly less code overall, but a bit more dense. Not sure which is preferable, so I'm looking for feedback on this PR

### CODE REVIEW

**Comment by Jamiewarb** [comment]
@liamb13 Any thoughts on this API mate? I feel like it's a bit easier to manage document actions, and makes them more distributable, as no need to handle action or schemaType logic in the action or around the calling code for the action. What do you think

**Comment by liamb13** [comment]
> "Prefer iteration and modularisation over code duplication." 
>
> [— <cite> Code Style and Structure</cite>](https://github.com/hex-digital/lucidity-next-sanity-starter/blob/c846cbd09009a97a7641ebd7994149d704872bcb/.cursorrules#L4)

Much prefer the API approach - it looks a lot cleaner, and takes the guess work out.

The only thing I'd reconsider is: 
> This API works best when you're **modifying existing Sanity document actions**. If you're only adding new ones, **you won't need this at all**.

Unless there's a good reason not to, why not handle creating new actions like this? It feels a lot cleaner than the alternative. Of course, devs will be free to do as they please, to me, this reads as though it should only be used for modifications.

Rather defineDocumentAction may be a better name, where adding the prop of action, then turns it into a modifier.  

I can't recall exact specifics as it was some time ago, but I remember a time when trying my hand creating a plugin became confusing when it got time to handle document actions. From memory it was as simple as my own custom actions were resetting the actions and disregarding the ones from the plugin. These are the little timely debugging tasks on a project that I think this starter could help overcome.

My only final thought, but it's not necessarily a requirement. I wonder how this would work if the actions were colocated in the schemas? Thinking 6 months after a project concludes or a new dev jumping in, if document actions are set within the schema's file, it may make things a little easier. Taking inspiration from the [Next.js way of setting Route Segment options](https://nextjs.org/docs/app/api-reference/file-conventions/route-segment-config#dynamic)

```
// schemas/page.ts
export const actions = {
  actions: ['publish'],
  schemaType: ['article'], // this may not be needed depending on how we then create the actions
  handler: setPublishDateAction,
};

export default defineType({
  name: 'article',
  type: 'document',
  title: 'Article',
  ...
});
```

Unsure if this creates a bigger mess though, especially with actions that should be applied on all schema types. What do you think? Could always be an aim for the future, as I recognize how complicated it might become.

**Comment by Jamiewarb** [comment]
Thanks so much for the feedback Liam!

On the topic of creating new document actions, currently this is even easier, as you just pass in an array to Sanity and it will automatically merge them.

If you need to both add new ones AND override existing ones, then this API would be useful. I believe that's covered already, but I haven't given it any special attention: you'd just merge your array with the one produced by the function provided in this PR. However, we could define new ones in the same format, with slightly different parameters, such as `type: 'new'` or `type: 'override'`. The helper functions could add that automatically. I'm just not sure if it's adding further complexity on top or if it's genuinely useful versus:

```
const docActions = (actions, context) => {
  return [
    ...modifyActions(actions, context, [/* actions */],
    myNewAction(),
  ];
}
```

On your last point, it's good thinking and I had a similar idea, but as an action can apply to multiple schemas, we'd then be co-locating only some of them and moving them if we needed to apply them to other schemas too. I thought it may be best to stick to a single convention of an `actions` directory due to the breadth of schemas they may cover.

**Comment by Jamiewarb** [comment]
I've updated some of the namings:

`modifyActions` -> `resolveActionPipeline`
`modifyActionsFn` -> `actionPipeline`

`defineActionModifier` -> `modifyAction`
`defineNewAction` -> `newAction`

**Pull request merged**
